version: '3.7'

services:

  minio:
    image: quay.io/minio/minio:RELEASE.2021-12-20T22-07-16Z
    hostname: minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes: minio-data
